### ISSUE TITLE
failed to call a cluster local  ksvc from an other ksvc which has istio sidecar injected in OCP.

### ISSUE THREAD

**Issue by csharpknife2002** [knative-sandbox/net-kourier#528]
I am using Knative serving (0.19) on OpenShift (4.6) and encount this issue.

In OCP, by default it uses the kourier for knative networking, and to use custom domain, I installed and use istio (OCP service mesh as well)
Now I have two ksvc:
the first one is an  public one, I followed the OCP document it works fine. 
custom domain => OCP IP => route for istio ingress => istio ingress => gateway => virtualservice => service entry => kourier => ksvc.
the second one is a cluster local one, which call be access from the cluster dns.

now both of them works fine, the first one can be accessed from outside by the domain, the second one can be accessed from other pods via internal dns. Except the first ksvc cannot access the second ksvc, since the first ksvc has an istio sidecar injected. if I disable the injection, the access will work, if I enable it, I will get the error message like this . 

`/usr/src/app $ wget http://internal-ksvc.stic-istio-demo-p4d.svc.cluster.local
Connecting to internal-ksvc.stic-istio-demo-p4d.svc.cluster.local (172.30.131.80:80)
wget: server returned error: HTTP/1.1 404 Not Found` 

when I chech the log from the 3scale-kourier-gateway pod, I can only get the good access record, I am not able to find anything related to 404 or failure logs.

Did I miss anything.

**Comment by nak3** [comment]
Hi @csharpknife2002

Thank you for your reporting. Let me ask you about your setup before debugging.

Since OpenShift Serverless 1.13 (serving 0.19), the custom domain is available by using DomainMapping[1], which does not need ServiceMesh at all. Have you already tried it but want to use the custom domain with ServiceMesh?

Also, sidecar injection is not mandatory even when you use custom domain with ServiceMesh. But you want to use sidecar injection for the first ksvc?

[1] https://docs.openshift.com/container-platform/4.7/serverless/serverless-release-notes.html#serverless-rn-1-13-0_serverless-release-notes
> A DomainMapping custom resource (CR) has been added to OpenShift Serverless to enable users to map a custom domain name to a Knative Service. See the Knative documentation on Creating a mapping between a custom domain name and a Knative Service.

**Comment by csharpknife2002** [comment]
Hi @nak3 ,
Thank you for your attension and reply.

Yes, I used the DomainMapping before, it works fine.  The reason of introduce ServiceMesh is not only for custom domain, it is mainly for the traffic control & multi-version support (we do have other non ksvc workload running in the same cluster). For istio side car I mainly want to use it for OAuth and TLS. 

I used the Knative + Istio for a while both in AKS and GKE, but for OCP , it is the first time for me to use the Knative + Kourier + Istio. Please let me know if I have any misunderstanding. 
 Thanks .

**Comment by csharpknife2002** [comment]
@nak3 , actually currently any service (ksvc or normal k8s service) as long as they are injected with istio sidecar, it won't able to access my ksvc using internal dns...

**Comment by nak3** [comment]
Hi @csharpknife2002 Thank you for your explanation. I understand.
And actually we realized that Knative + Kourier + Istio makes very complicated structure and so we have a plan to support to choose net-istio or net-kourier on OpenShift. I think that you should use net-istio instead of net-kourier in your use-case.
Can we discuss it in Slack https://slack.knative.dev/. If you are alright, please join the Slack and ping to me (@nak3).
