### ISSUE TITLE
Determine the process of how/what envoy configurations we support

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-kourier#892]
There are some requests to add a new Envoy configuration on Kourier recently.
But we don't have the process of how/what envoy configurations we support and so the new configurations could mess up the Kourier code and cause confusion why this is supported but why this is not.
We should determine the process.

### How to support the configuration

In many cases, the configuration could be supported by introducing a new annotation.
However, the annotation solution is a double-edged sword, which means easy to add but mess up the configuration. (we will eventually support a ton of the annotations).
Is there any better way?

### What envoy feature/configuration support

There are so many envoy configurations. We probably need to select some of them with a criteria such as many users requested, critical configurations and so on.

**Comment by xxinran** [comment]
Thanks to bring it up here.  I agree that we do not need to support all envoy configurations, we could start by adding the most used ones.
To avoid annotation messing up, we may need to add some validation function to filter out the invalid options. 
Otherwise, we could add configurations in `config-kourier`.

**Comment by daisy-ycguo** [comment]
According to the question "What envoy feature/configuration support" I have a suggestion.  We developers will not make the decision instead of users. Let users make the decision. We just provide a way for users to set a custom envoy bootstrap configuration and then we create kourier bootstrap configuration based on users custom configuration. Thus users could decide which configurations he wants to set.

For example, a user can create a configmap with his bootstrap configuration to support both configuring envoy connection parameters and configuring private key providers, e.g.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-bootstrap-config
  namespace: kourier-system
data:
  custom_bootstrap.json: |
    "static_resources": {
      "clusters": {
        "circuit_breakers": {
          "thresholds": {
            "priority": ...,
            "max_connections": {...},
            "max_pending_requests": {...},
            "max_requests": {...},
            "max_retries": {...},
          }
        }
      }
      "secrets": {
        "tls_certificate": {
          "private_key": {...},
          "private_key_provider": {...},
        }
      }
    }
```

Obviously, the disadvantage of this solution is that users need to learn Envoy bootstrap configuration. But it will not mess up Kourier codes and gives the most flexibility to Kourier users to config envoy.
